### ISSUE TITLE
 java.lang.NullPointerException when use library

### ISSUE THREAD

**Issue by kamyar75** [asapJ/Flutter_Thumbnails#12]
W/System.err(25430): java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
W/System.err(25430): 	at java.util.regex.Matcher.reset(Matcher.java:280)
W/System.err(25430): 	at java.util.regex.Matcher.<init>(Matcher.java:186)
W/System.err(25430): 	at java.util.regex.Pattern.matcher(Pattern.java:1034)
W/System.err(25430): 	at com.asapjay.thumbnails.ThumbnailsPlugin.getFileName(ThumbnailsPlugin.java:176)
W/System.err(25430): 	at com.asapjay.thumbnails.ThumbnailsPlugin.cacheDirectory(ThumbnailsPlugin.java:70)
W/System.err(25430): 	at com.asapjay.thumbnails.ThumbnailsPlugin.buildThumbnail(ThumbnailsPlugin.java:64)
W/System.err(25430): 	at com.asapjay.thumbnails.ThumbnailsPlugin.onMethodCall(ThumbnailsPlugin.java:49)
W/System.err(25430): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
W/System.err(25430): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
W/System.err(25430): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
W/System.err(25430): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(25430): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err(25430): 	at android.os.Looper.loop(Looper.java:174)
W/System.err(25430): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(25430): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(25430): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err(25430): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by marianoarga** [comment]
Same here
