### ISSUE TITLE
How to get the example working?

### ISSUE THREAD

**Issue by armanm** [asapJ/Flutter_Thumbnails#2]
I've been running the example in this repo but when I press either buttons, this is the log I get. I suspect this is something to do with the location of the source video file but don't know what to do about it. Could you please add more detail to your example so it's clear how to get it working for a noob like me 🙇 ?

```
W/System.err(10797): java.io.FileNotFoundException: /storage/emulated/0/Videos/Thumbnails/Testvideo.png (No such file or directory)
W/System.err(10797): 	at java.io.FileOutputStream.open0(Native Method)
W/System.err(10797): 	at java.io.FileOutputStream.open(FileOutputStream.java:308)
W/System.err(10797): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
W/System.err(10797): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
W/System.err(10797): 	at com.asapjay.thumbnails.ThumbnailsPlugin.userDirectory(ThumbnailsPlugin.java:137)
W/System.err(10797): 	at com.asapjay.thumbnails.ThumbnailsPlugin.buildThumbnail(ThumbnailsPlugin.java:64)
W/System.err(10797): 	at com.asapjay.thumbnails.ThumbnailsPlugin.onMethodCall(ThumbnailsPlugin.java:49)
W/System.err(10797): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
W/System.err(10797): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
W/System.err(10797): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(10797): 	at android.os.MessageQueue.next(MessageQueue.java:326)
W/System.err(10797): 	at android.os.Looper.loop(Looper.java:160)
W/System.err(10797): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
W/System.err(10797): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(10797): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err(10797): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (10797): path to File:
W/System.err(10797): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
W/System.err(10797): 	at com.asapjay.thumbnails.ThumbnailsPlugin.cacheDirectory(ThumbnailsPlugin.java:82)
W/System.err(10797): 	at com.asapjay.thumbnails.ThumbnailsPlugin.buildThumbnail(ThumbnailsPlugin.java:64)
W/System.err(10797): 	at com.asapjay.thumbnails.ThumbnailsPlugin.onMethodCall(ThumbnailsPlugin.java:49)
W/System.err(10797): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
W/System.err(10797): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
W/System.err(10797): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(10797): 	at android.os.MessageQueue.next(MessageQueue.java:326)
W/System.err(10797): 	at android.os.Looper.loop(Looper.java:160)
W/System.err(10797): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
W/System.err(10797): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(10797): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err(10797): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by armanm** [comment]
I seem to have finally figured it out. Here are the things that I eventually realised were needed:

1. trigger the permission prompts and allowing access to storage - used the [simple_permissions](https://pub.dartlang.org/packages/simple_permissions) package
2. find a path to a video file – `getExternalStorageDirectory().listSync(recursive: true)` from the [path_provider](https://pub.dartlang.org/packages/path_provider) package was handy for that
3. provide a valid location for `thumbnailFolder` option

**Comment by ameeee** [comment]
Hi @armanm 
Can you please provide an example of your solution?

**Comment by kamleshwebtech** [comment]
I am still getting below issue: 

```
W/System.err( 2412): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
W/System.err( 2412): 	at com.asapjay.thumbnails.ThumbnailsPlugin.userDirectory(ThumbnailsPlugin.java:138)
W/System.err( 2412): 	at com.asapjay.thumbnails.ThumbnailsPlugin.buildThumbnail(ThumbnailsPlugin.java:64)
W/System.err( 2412): 	at com.asapjay.thumbnails.ThumbnailsPlugin.onMethodCall(ThumbnailsPlugin.java:49)
W/System.err( 2412): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/System.err( 2412): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err( 2412): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
W/System.err( 2412): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 2412): 	at android.os.MessageQueue.next(MessageQueue.java:329)
W/System.err( 2412): 	at android.os.Looper.loop(Looper.java:142)
W/System.err( 2412): 	at android.app.ActivityThread.main(ActivityThread.java:6375)
W/System.err( 2412): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 2412): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
W/System.err( 2412): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

and my function is as:

```
getVideoUrlToThumbUrl(videoPathUrl) async {
    if (await getFileType(videoPathUrl) != CONST_APP_FILE_TYPE_VIDEO) {
      return '';
    }
    final docDirectory = await getApplicationDocumentsDirectory();
    String videothumbnailsPath = docDirectory.path + '/videothumbnails';

    // String videothumbnailsPath = CONST_APP_ED_VIDEO_PATH;

    File file = new File(videoPathUrl);
    String fileName = file.path.split('/').last;
    fileName = fileName.replaceFirst('.mp4', '.png');
    var isThumbExists =
        await io.File(videothumbnailsPath + '/' + fileName).exists();
    String vdoPath = '';
    if (isThumbExists == false) {
      vdoPath = await Thumbnails.getThumbnail(
          thumbnailFolder: videothumbnailsPath,
          videoFile: videoPathUrl,
          imageType: ThumbFormat.PNG,
          quality: 10);
    } else {
      vdoPath = videothumbnailsPath + '/' + fileName;
    }
    return vdoPath;
  }
```

Any solution, please share. Thanks a lot.
